metwork-framework/mfserv

adm/__make_nginx_conf, config/nginx.conf
integration of @duretf #8 branch
=> integration of @duretf #8 branch

adm/__make_nginx_conf
=> fix: fix lua lib paths

adm/conf_monitor.sh
=> fix: fix timeout issues around conf_monitor restarts

adm/__make_nginx_conf, adm/templates/plugins/static/cookiecutter.json, adm/templates/plugins/static/hooks/post_gen_project.py, adm/templates/plugins/static/{{cookiecutter.name}}/.layerapi2_dependencies, adm/templates/plugins/static/{{cookiecutter.name}}/.layerapi2_label, adm/templates/plugins/static/{{cookiecutter.name}}/Makefile, adm/templates/plugins/static/{{cookiecutter.name}}/config.ini, adm/templates/plugins/static/{{cookiecutter.name}}/main/index.html, config/nginx.conf
=> feat: Add static plugin type and corresponding template

integration_tests/0001_test_mfserv_operational/test_mfserv_operational.sh
(are mfserv.start/status/stop working ?)
work on #52
=> build: add basic mfserv integration test

.gitignore
The branch name "issue127" is not relevent...
=> build: update .gitignore

adm/_make_circus_conf
See metwork-framework/resources#24
=> [WIP] refactor: use new plugin_wrapper

config/circus.ini.custom
About metwork-framework/mfcom#82
=> [WIP] build: use new mfcom plugin

adm/conf_monitor.py
please merge linked to metwork-framework/mfcom#92 before
=> fix: more reliable nginx reload in conf_monitor

adm/mfserv_conf_monitor.py, adm/mfxxx.status.custom, config/circus.ini.custom, config/config.ini
Can be useful for very special use cases.
=> feat: we can deactivate the nginx startup

adm/_make_nginx_conf, config/config.ini, config/nginx.conf
=> feat: nginx logs are now in JSON to prepare mfadmin#16

adm/templates/plugins/default/cookiecutter.json, adm/templates/plugins/django/cookiecutter.json, adm/templates/plugins/empty/cookiecutter.json, adm/templates/plugins/node/cookiecutter.json, adm/templates/plugins/nodets/cookiecutter.json, adm/templates/plugins/static/cookiecutter.json
The name is already given on the CLI.
See metwork-framework/mfcom#111
=> feat: remove "name" from the list of questions during plugin bootstrap

adm/__make_nginx_conf, config/config.ini, config/nginx.conf
=> feat: add global nginx timeout configuration

adm/_make_circus_conf
=> feat: split multiple node workers output to multiple files

adm/templates/plugins/django/cookiecutter.json
=> fix: django template regression when bootstrapping

adm/_make_circus_conf
=> feat: remove double access-log messages with gunicorn

adm/_make_circus_conf
If the value was over 30s.
Close: #163
=> fix: proxy_timeout was bypassed by gunicorn sync configurations

config/circus.ini.custom
=> fix: add the missing line for numprocesses

adm/bjoern_wrapper.py, config/config.ini, config/nginx.conf
=> feat: add proxy_ignore_client_abort option

config/nginx.conf
=> fix: typo with virtualdomain based routing

adm/templates/plugins/_common/python2_virtualenv_sources.delete, adm/templates/plugins/_common/python3_virtualenv_sources.delete
=> fix: more precise condition to delete python-requirement

adm/Makefile, adm/__make_nginx_conf, adm/_make_circus_conf, adm/mfxxx.start.custom, adm/plugins.hotswap, config/circus.ini.custom, integration_tests/0020_hotswap/test.py
=> feat: plugins.hotswap feature!

adm/_make_nginx_conf
=> build: fix welcome plugin installation issue during the very first start

adm/__make_nginx_conf
=> build: improve backward compatibility for MODULE_* => MFMODULE_*

config/config.ini, config/nginx.conf
=> feat: add nginx/server_tokens option in config

adm/_check_nginx_conf, config/config.ini
=> feat: add a warning if nginx/port is < 1024

config/socket_updown.lua
We are now able to use "non unix socket" load balancing
=> feat: little improvment in socket up/down feature

adm/templates/plugins/empty/cookiecutter.json, adm/templates/plugins/empty/{{cookiecutter.name}}/bin/README, doc/mfserv_create_plugins.md, integration_tests/0011_extra_daemon/test.py
=> feat: improve empty plugin template and update documentation

adm/Makefile, adm/_make_circus_conf, adm/signal_wrapper.py, config/socket_updown.lua
Specially with aiohttp backend (the feature was not really implemented
for this backend).
Close: #286
=> fix: important fix about max_age feature

adm/_make_circus_conf, adm/signal_wrapper.py, config/circus.ini.custom
for backends wrapped with signal_wrapper.
It fixes some zombies problems during dev sessions.
=> fix: change the stop signal with autorestart dev feature

adm/signal_wrapper.py
=> fix: fix signal_wrapper in python2

adm/__make_nginx_conf, adm/_make_circus_conf, adm/_plugins.is_dangerous
See metwork-framework/resources#52
=> build: configparser_extend drop

config/config.ini.custom, config/nginx.conf
=> feat: new accept_incoming_request_id_header variable and x-forwarded-*

adm/_check_nginx_conf
=> fix: don't prevent nginx to bind <1024 port (with setcap)

config/nginx.conf
backport of #424, see issue #423
=> fix: bug with static files when extra_route is set to /

adm/_check_nginx_conf, adm/_make_nginx_conf, config/nginx.conf
if you have an old configuration without https keys
=> fix: fix some rare https configuration issues

adm/templates/plugins/_common/config.ini
=> fix: fix bad comment in boostrapped config.ini for plugins

adm/plugins.py, adm/templates/plugins/_common/config.ini
when the virtualhost is different than the machine name
=> fix: fix virtualhosting usage

config/Makefile
=> fix: fix error message in nginx error log

config/nginx.conf
see https://github.com/openresty/lua-nginx-module/issues/1301
=> fix: fix a complex issue about nginx var caching

adm/_check_nginx_conf
=> build: fix for getcap 2.48

config/nginx.conf
=> fix: regression on static routing (#576)

config/config.ini.custom, config/nginx.conf
=> feat: add support of the nginx port_in_redirect directive
